/*===========================================================================*/
/* Module      = DF4010_irq.h                                                */
/* Version     = E1.00f_patch1                                                      */
/*               extracted from device file DF4010.800                       */
/*               generated by DeFiXE2 0.8.5.3                                */
/*===========================================================================*/
/*                                  COPYRIGHT                                */
/*===========================================================================*/
/* Copyright (c) 2010 by Renesas Electronics Europe GmbH,                    */
/*               a company of the Renesas Electronics Corporation            */
/*===========================================================================*/
/* Purpose:      Declarations of Interrupt Vector Table                      */
/*                                                                           */
/*===========================================================================*/
/*                                                                           */
/* Warranty Disclaimer                                                       */
/*                                                                           */
/* Because the Product(s) is licensed free of charge, there is no warranty   */
/* of any kind whatsoever and expressly disclaimed and excluded by Renesas,  */
/* either expressed or implied, including but not limited to those for       */
/* non-infringement of intellectual property, merchantability and/or         */
/* fitness for the particular purpose.                                       */
/* Renesas shall not have any obligation to maintain, service or provide bug */
/* fixes for the supplied Product(s) and/or the Application.                 */
/*                                                                           */
/* Each User is solely responsible for determining the appropriateness of    */
/* using the Product(s) and assumes all risks associated with its exercise   */
/* of rights under this Agreement, including, but not limited to the risks   */
/* and costs of program errors, compliance with applicable laws, damage to   */
/* or loss of data, programs or equipment, and unavailability or             */
/* interruption of operations.                                               */
/*                                                                           */
/* Limitation of Liability                                                   */
/*                                                                           */
/* In no event shall Renesas be liable to the User for any incidental,       */
/* consequential, indirect, or punitive damage (including but not limited    */
/* to lost profits) regardless of whether such liability is based on breach  */
/* of contract, tort, strict liability, breach of warranties, failure of     */
/* essential purpose or otherwise and even if advised of the possibility of  */
/* such damages. Renesas shall not be liable for any services or products    */
/* provided by third party vendors, developers or consultants identified or  */
/* referred to the User by Renesas in connection with the Product(s) and/or  */
/* the Application.                                                          */
/*                                                                           */
/*===========================================================================*/
/* Environment:                                                              */
/*              Device:         UPD70F4010                                   */
/*              IDE:            GHS Multi for V800                           */
/*===========================================================================*/

#ifndef __UPD70F4010_IRQ_H
#define __UPD70F4010_IRQ_H

#define RESET_ENABLE                    0x00000001
// #define SYSCALLEX_ENABLE                0x00000001
 
#ifndef RESET_ENABLE                   
  #define RESET_ENABLE                    0x00000000
#endif
#ifndef SYSCALLEX_ENABLE               
  #define SYSCALLEX_ENABLE                0x00000000
#endif
#if ( RESET_ENABLE + SYSCALLEX_ENABLE) > 0x00000001
 #error Too many exception causes defined!
#endif

// #define FEINT_ENABLE                    0x00000010

// #define NMI0_ENABLE                     0x00000020
// #define WDTA0TNMI_ENABLE                0x00000020
// #define WDTA1TNMI_ENABLE                0x00000020
 
#ifndef NMI0_ENABLE                    
  #define NMI0_ENABLE                     0x00000000
#endif
#ifndef WDTA0TNMI_ENABLE               
  #define WDTA0TNMI_ENABLE                0x00000000
#endif
#ifndef WDTA1TNMI_ENABLE               
  #define WDTA1TNMI_ENABLE                0x00000000
#endif
#if ( NMI0_ENABLE + WDTA0TNMI_ENABLE + WDTA1TNMI_ENABLE) > 0x00000020
 #error Too many exception causes defined!
#endif

// #define FETRAPEX_ENABLE                 0x00000030
// #define MDP_ENABLE                      0x00000030
// #define MEP_ENABLE                      0x00000030
// #define MIP_ENABLE                      0x00000030
// #define PPI_ENABLE                      0x00000030
// #define RIEX_ENABLE                     0x00000030
// #define SYSERR_ENABLE                   0x00000030
// #define TSI_ENABLE                      0x00000030
// #define UCPOP_ENABLE                    0x00000030
 
#ifndef FETRAPEX_ENABLE                
  #define FETRAPEX_ENABLE                 0x00000000
#endif
#ifndef MDP_ENABLE                     
  #define MDP_ENABLE                      0x00000000
#endif
#ifndef MEP_ENABLE                     
  #define MEP_ENABLE                      0x00000000
#endif
#ifndef MIP_ENABLE                     
  #define MIP_ENABLE                      0x00000000
#endif
#ifndef PPI_ENABLE                     
  #define PPI_ENABLE                      0x00000000
#endif
#ifndef RIEX_ENABLE                    
  #define RIEX_ENABLE                     0x00000000
#endif
#ifndef SYSERR_ENABLE                  
  #define SYSERR_ENABLE                   0x00000000
#endif
#ifndef TSI_ENABLE                     
  #define TSI_ENABLE                      0x00000000
#endif
#ifndef UCPOP_ENABLE                   
  #define UCPOP_ENABLE                    0x00000000
#endif
#if ( FETRAPEX_ENABLE + MDP_ENABLE + MEP_ENABLE + MIP_ENABLE + PPI_ENABLE + RIEX_ENABLE + SYSERR_ENABLE + TSI_ENABLE + UCPOP_ENABLE) > 0x00000030
 #error Too many exception causes defined!
#endif

// #define EITRAP0_ENABLE                  0x00000040

// #define EITRAP1_ENABLE                  0x00000050

// #define ASYNCDB_ENABLE                  0x00000060
// #define DBTRAPEX_ENABLE                 0x00000060
// #define SS_ENABLE                       0x00000060
// #define SYNCDB_ENABLE                   0x00000060
 
#ifndef ASYNCDB_ENABLE                 
  #define ASYNCDB_ENABLE                  0x00000000
#endif
#ifndef DBTRAPEX_ENABLE                
  #define DBTRAPEX_ENABLE                 0x00000000
#endif
#ifndef SS_ENABLE                      
  #define SS_ENABLE                       0x00000000
#endif
#ifndef SYNCDB_ENABLE                  
  #define SYNCDB_ENABLE                   0x00000000
#endif
#if ( ASYNCDB_ENABLE + DBTRAPEX_ENABLE + SS_ENABLE + SYNCDB_ENABLE) > 0x00000060
 #error Too many exception causes defined!
#endif

// #define FPI_ENABLE                      0x00000070
// #define FPP_ENABLE                      0x00000070
 
#ifndef FPI_ENABLE                     
  #define FPI_ENABLE                      0x00000000
#endif
#ifndef FPP_ENABLE                     
  #define FPP_ENABLE                      0x00000000
#endif
#if ( FPI_ENABLE + FPP_ENABLE) > 0x00000070
 #error Too many exception causes defined!
#endif

// #define INTWDTA0_ENABLE                 0x00000080

// #define INTWDTA1_ENABLE                 0x00000090

// #define INTLVI_ENABLE                   0x000000A0

// #define INTVCPC0_ENABLE                 0x000000C0

// #define INTVCPC1_ENABLE                 0x000000D0

// #define INTRTCA01S_ENABLE               0x000000E0

// #define INTRTCA0AL_ENABLE               0x000000F0

// #define INTRTCA0R_ENABLE                0x00000100

// #define INTP0_ENABLE                    0x00000110

// #define INTP1_ENABLE                    0x00000120

// #define INTP2_ENABLE                    0x00000130

// #define INTP3_ENABLE                    0x00000140

// #define INTP4_ENABLE                    0x00000150

// #define INTP5_ENABLE                    0x00000160

// #define INTP6_ENABLE                    0x00000170

// #define INTP7_ENABLE                    0x00000180

// #define INTP8_ENABLE                    0x00000190

// #define INTP9_ENABLE                    0x000001A0

// #define INTP10_ENABLE                   0x000001B0

// #define INTTAPA0IPEK0_ENABLE            0x000001C0
// #define INTTAUA0I0_ENABLE               0x000001C0
 
#ifndef INTTAPA0IPEK0_ENABLE           
  #define INTTAPA0IPEK0_ENABLE            0x00000000
#endif
#ifndef INTTAUA0I0_ENABLE              
  #define INTTAUA0I0_ENABLE               0x00000000
#endif
#if ( INTTAPA0IPEK0_ENABLE + INTTAUA0I0_ENABLE) > 0x000001C0
 #error Too many exception causes defined!
#endif

// #define INTTAUA0I1_ENABLE               0x000001D0

// #define INTTAUA0I2_ENABLE               0x000001E0

// #define INTTAUA0I3_ENABLE               0x000001F0

// #define INTTAPA0IVLY0_ENABLE            0x00000200

// #define INTTAUA0I4_ENABLE               0x00000200

// #define INTTAUA0I5_ENABLE               0x00000210

// #define INTTAUA0I6_ENABLE               0x00000220

// #define INTTAUA0I7_ENABLE               0x00000230

// #define INTTAUA0I8_ENABLE               0x00000240

// #define INTTAUA0I9_ENABLE               0x00000250

// #define INTTAUA0I10_ENABLE              0x00000260

// #define INTTAUA0I11_ENABLE              0x00000270

// #define INTTAUA0I12_ENABLE              0x00000280

// #define INTTAUA0I13_ENABLE              0x00000290

// #define INTTAUA0I14_ENABLE              0x000002A0

// #define INTTAUA0I15_ENABLE              0x000002B0

// #define INTTAUB1I0_ENABLE               0x000002C0

// #define INTTAUB1I1_ENABLE               0x000002D0

// #define INTTAUB1I2_ENABLE               0x000002E0

// #define INTTAUB1I3_ENABLE               0x000002F0

// #define INTTAUB1I4_ENABLE               0x00000300

// #define INTTAUB1I5_ENABLE               0x00000310

// #define INTTAUB1I6_ENABLE               0x00000320

// #define INTTAUB1I7_ENABLE               0x00000330

// #define INTTAUB1I8_ENABLE               0x00000340

// #define INTTAUB1I9_ENABLE               0x00000350

// #define INTTAUB1I10_ENABLE              0x00000360

// #define INTTAUB1I11_ENABLE              0x00000370

// #define INTTAUB1I12_ENABLE              0x00000380

// #define INTTAUB1I13_ENABLE              0x00000390

// #define INTTAUB1I14_ENABLE              0x000003A0

// #define INTTAUB1I15_ENABLE              0x000003B0

// #define INTTAUC2I0_ENABLE               0x000003C0

// #define INTTAUC2I1_ENABLE               0x000003D0

// #define INTTAUC2I2_ENABLE               0x000003E0

// #define INTTAUC2I3_ENABLE               0x000003F0

// #define INTTAUC2I4_ENABLE               0x00000400

// #define INTTAUC2I5_ENABLE               0x00000410

// #define INTTAUC2I6_ENABLE               0x00000420

// #define INTTAUC2I7_ENABLE               0x00000430

// #define INTTAUC2I8_ENABLE               0x00000440

// #define INTTAUC2I9_ENABLE               0x00000450

// #define INTTAUC2I10_ENABLE              0x00000460

// #define INTTAUC2I11_ENABLE              0x00000470

// #define INTTAUC2I12_ENABLE              0x00000480

// #define INTTAUC2I13_ENABLE              0x00000490

// #define INTTAUC2I14_ENABLE              0x000004A0

// #define INTTAUC2I15_ENABLE              0x000004B0

// #define INTTAUC3I0_ENABLE               0x000004C0

// #define INTTAUC3I1_ENABLE               0x000004D0

// #define INTTAUC3I2_ENABLE               0x000004E0

// #define INTTAUC3I3_ENABLE               0x000004F0

// #define INTTAUC3I4_ENABLE               0x00000500

// #define INTTAUC3I5_ENABLE               0x00000510

// #define INTTAUC3I6_ENABLE               0x00000520

// #define INTTAUC3I7_ENABLE               0x00000530

// #define INTTAUC3I8_ENABLE               0x00000540

// #define INTTAUC3I9_ENABLE               0x00000550

// #define INTTAUC3I10_ENABLE              0x00000560

// #define INTTAUC3I11_ENABLE              0x00000570

// #define INTTAUC3I12_ENABLE              0x00000580

// #define INTTAUC3I13_ENABLE              0x00000590

// #define INTTAUC3I14_ENABLE              0x000005A0

// #define INTTAUC3I15_ENABLE              0x000005B0

// #define INTTAUC4I0_ENABLE               0x000005C0

// #define INTTAUC4I1_ENABLE               0x000005D0

// #define INTTAUC4I2_ENABLE               0x000005E0

// #define INTTAUC4I3_ENABLE               0x000005F0

// #define INTTAUC4I4_ENABLE               0x00000600

// #define INTTAUC4I5_ENABLE               0x00000610

// #define INTTAUC4I6_ENABLE               0x00000620

// #define INTTAUC4I7_ENABLE               0x00000630

// #define INTTAUC4I8_ENABLE               0x00000640

// #define INTTAUC4I9_ENABLE               0x00000650

// #define INTTAUC4I10_ENABLE              0x00000660

// #define INTTAUC4I11_ENABLE              0x00000670

// #define INTTAUC4I12_ENABLE              0x00000680

// #define INTTAUC4I13_ENABLE              0x00000690

// #define INTTAUC4I14_ENABLE              0x000006A0

// #define INTTAUC4I15_ENABLE              0x000006B0

// #define INTADCA0ERR_ENABLE              0x000006C0

// #define INTADCA0I0_ENABLE               0x000006D0

// #define INTADCA0I1_ENABLE               0x000006E0

// #define INTADCA0I2_ENABLE               0x000006F0

// #define INTADCA0LLT_ENABLE              0x00000700

// #define INTFCNWUP_ENABLE                0x00000710

// #define INTFCN0ERR_ENABLE               0x00000720

// #define INTFCN0REC_ENABLE               0x00000730

// #define INTFCN0TRX_ENABLE               0x00000740

// #define INTCSIG0IRE_ENABLE              0x00000750

// #define INTCSIG0IR_ENABLE               0x00000760

// #define INTCSIG0IC_ENABLE               0x00000770

// #define INTADCA1ERR_ENABLE              0x000007E0

// #define INTCT0_ENABLE                   0x000007F0
// #define INTDMA0_ENABLE                  0x000007F0
 
#ifndef INTCT0_ENABLE                  
  #define INTCT0_ENABLE                   0x00000000
#endif
#ifndef INTDMA0_ENABLE                 
  #define INTDMA0_ENABLE                  0x00000000
#endif
#if ( INTCT0_ENABLE + INTDMA0_ENABLE) > 0x000007F0
 #error Too many exception causes defined!
#endif

// #define INTCT1_ENABLE                   0x00000800
// #define INTDMA1_ENABLE                  0x00000800
 
#ifndef INTCT1_ENABLE                  
  #define INTCT1_ENABLE                   0x00000000
#endif
#ifndef INTDMA1_ENABLE                 
  #define INTDMA1_ENABLE                  0x00000000
#endif
#if ( INTCT1_ENABLE + INTDMA1_ENABLE) > 0x00000800
 #error Too many exception causes defined!
#endif

// #define INTCT2_ENABLE                   0x00000810
// #define INTDMA2_ENABLE                  0x00000810
 
#ifndef INTCT2_ENABLE                  
  #define INTCT2_ENABLE                   0x00000000
#endif
#ifndef INTDMA2_ENABLE                 
  #define INTDMA2_ENABLE                  0x00000000
#endif
#if ( INTCT2_ENABLE + INTDMA2_ENABLE) > 0x00000810
 #error Too many exception causes defined!
#endif

// #define INTCT3_ENABLE                   0x00000820
// #define INTDMA3_ENABLE                  0x00000820
 
#ifndef INTCT3_ENABLE                  
  #define INTCT3_ENABLE                   0x00000000
#endif
#ifndef INTDMA3_ENABLE                 
  #define INTDMA3_ENABLE                  0x00000000
#endif
#if ( INTCT3_ENABLE + INTDMA3_ENABLE) > 0x00000820
 #error Too many exception causes defined!
#endif

// #define INTCT4_ENABLE                   0x00000830
// #define INTDMA4_ENABLE                  0x00000830
 
#ifndef INTCT4_ENABLE                  
  #define INTCT4_ENABLE                   0x00000000
#endif
#ifndef INTDMA4_ENABLE                 
  #define INTDMA4_ENABLE                  0x00000000
#endif
#if ( INTCT4_ENABLE + INTDMA4_ENABLE) > 0x00000830
 #error Too many exception causes defined!
#endif

// #define INTCT5_ENABLE                   0x00000840
// #define INTDMA5_ENABLE                  0x00000840
 
#ifndef INTCT5_ENABLE                  
  #define INTCT5_ENABLE                   0x00000000
#endif
#ifndef INTDMA5_ENABLE                 
  #define INTDMA5_ENABLE                  0x00000000
#endif
#if ( INTCT5_ENABLE + INTDMA5_ENABLE) > 0x00000840
 #error Too many exception causes defined!
#endif

// #define INTCT6_ENABLE                   0x00000850
// #define INTDMA6_ENABLE                  0x00000850
 
#ifndef INTCT6_ENABLE                  
  #define INTCT6_ENABLE                   0x00000000
#endif
#ifndef INTDMA6_ENABLE                 
  #define INTDMA6_ENABLE                  0x00000000
#endif
#if ( INTCT6_ENABLE + INTDMA6_ENABLE) > 0x00000850
 #error Too many exception causes defined!
#endif

// #define INTCT7_ENABLE                   0x00000860
// #define INTDMA7_ENABLE                  0x00000860
 
#ifndef INTCT7_ENABLE                  
  #define INTCT7_ENABLE                   0x00000000
#endif
#ifndef INTDMA7_ENABLE                 
  #define INTDMA7_ENABLE                  0x00000000
#endif
#if ( INTCT7_ENABLE + INTDMA7_ENABLE) > 0x00000860
 #error Too many exception causes defined!
#endif

// #define INTFL_ENABLE                    0x00000870

// #define INTIICB0IA_ENABLE               0x00000890

// #define INTFCN1ERR_ENABLE               0x000008C0

// #define INTFCN1REC_ENABLE               0x000008D0

// #define INTFCN1TRX_ENABLE               0x000008E0

// #define INTTAUJ0I0_ENABLE               0x000008F0

// #define INTTAUJ0I1_ENABLE               0x00000900

// #define INTTAUJ0I2_ENABLE               0x00000910

// #define INTTAUJ0I3_ENABLE               0x00000920

// #define INTTAUJ1I0_ENABLE               0x00000930

// #define INTTAUJ1I1_ENABLE               0x00000940

// #define INTTAUJ1I2_ENABLE               0x00000950

// #define INTTAUJ1I3_ENABLE               0x00000960

// #define INTADCA1I0_ENABLE               0x00000970

// #define INTADCA1I1_ENABLE               0x00000980

// #define INTADCA1I2_ENABLE               0x00000990

// #define INTADCA1LLT_ENABLE              0x000009A0

 #define INTOSTM0_ENABLE                 0x000009B0

// #define INTFCN3ERR_ENABLE               0x00000A20

// #define INTFCN3REC_ENABLE               0x00000A30

// #define INTFCN3TRX_ENABLE               0x00000A40

// #define INTFCN2ERR_ENABLE               0x00000A80

// #define INTFCN2REC_ENABLE               0x00000A90

// #define INTFCN2TRX_ENABLE               0x00000AA0

// #define INTCSIH0IC_ENABLE               0x00000AB0

// #define INTCSIH0IJC_ENABLE              0x00000AC0

// #define INTCSIH0IRE_ENABLE              0x00000B00

// #define INTCSIH0IR_ENABLE               0x00000B10

// #define INTCSIG4IRE_ENABLE              0x00000B20

// #define INTCSIG4IR_ENABLE               0x00000B30

// #define INTCSIG4IC_ENABLE               0x00000B40

// #define INTFLXA0I0_ENABLE               0x00000B80

// #define INTFLXA0I1_ENABLE               0x00000B90

// #define INTFLXA0I2_ENABLE               0x00000BA0

// #define INTFLXA0I3_ENABLE               0x00000BB0

// #define INTCSIH1IRE_ENABLE              0x00000BC0

// #define INTCSIH1IR_ENABLE               0x00000BD0

// #define INTCSIH1IC_ENABLE               0x00000BE0

// #define INTCSIH1IJC_ENABLE              0x00000BF0

// #define INTENCA0I0_ENABLE               0x00000C30

// #define INTENCA0I1_ENABLE               0x00000C40

// #define INTENCA0IUD_ENABLE              0x00000C50

// #define INTENCA0IEC_ENABLE              0x00000C60

// #define INTENCA0IOV_ENABLE              0x00000C70

// #define INTLMA2IS_ENABLE                0x00000C90

// #define INTLMA2IR_ENABLE                0x00000CA0

// #define INTLMA2IT_ENABLE                0x00000CB0

// #define INTLMA3IS_ENABLE                0x00000CC0

// #define INTLMA3IR_ENABLE                0x00000CD0

// #define INTLMA3IT_ENABLE                0x00000CE0

// #define INTLMA4IS_ENABLE                0x00000CF0

// #define INTLMA4IR_ENABLE                0x00000D00

// #define INTLMA4IT_ENABLE                0x00000D10

// #define INTCSIH2IRE_ENABLE              0x00000D20

// #define INTCSIH2IR_ENABLE               0x00000D30

// #define INTCSIH2IC_ENABLE               0x00000D40

// #define INTCSIH2IJC_ENABLE              0x00000D50

// #define INTP11_ENABLE                   0x00000D80

// #define INTP12_ENABLE                   0x00000D90

// #define INTP13_ENABLE                   0x00000DA0

// #define INTP14_ENABLE                   0x00000DB0

// #define INTP15_ENABLE                   0x00000DC0

// #define INTKR0_ENABLE                   0x00000E40

// #define INTLMA5IS_ENABLE                0x00000E90

// #define INTLMA5IR_ENABLE                0x00000EA0

// #define INTLMA5IT_ENABLE                0x00000EB0

// #define INTLMA6IS_ENABLE                0x00000F40

// #define INTLMA6IR_ENABLE                0x00000F50

// #define INTLMA6IT_ENABLE                0x00000F60

// #define INTLMA7IS_ENABLE                0x00000F70

// #define INTLMA7IR_ENABLE                0x00000F80

// #define INTLMA7IT_ENABLE                0x00000F90

// #define INTLMA10IS_ENABLE               0x00001000

// #define INTLMA10IR_ENABLE               0x00001010

// #define INTLMA10IT_ENABLE               0x00001020

// #define INTLMA11IS_ENABLE               0x00001030

// #define INTLMA11IR_ENABLE               0x00001040

// #define INTLMA11IT_ENABLE               0x00001050

// #define INTFLR_ENABLE                   0x00001060



#endif /* __UPD70F4010_IRQ_H */
