
#ifndef SCHM_CANSM_H
#define SCHM_CANSM_H

#include "SchM.h"
#include "SchM_Types.h"
#include "SchM_Cfg.h"


#define CANSM_EXCLUSIVE_AREA_0   SCHM_EA_SUSPENDALLINTERRUPTS
#define CANSM_EXCLUSIVE_AREA_1   SCHM_EA_SUSPENDALLINTERRUPTS
#define CANSM_EXCLUSIVE_AREA_2   SCHM_EA_SUSPENDALLINTERRUPTS
#define CANSM_EXCLUSIVE_AREA_3   SCHM_EA_SUSPENDALLINTERRUPTS
#define CANSM_EXCLUSIVE_AREA_4   SCHM_EA_SUSPENDALLINTERRUPTS
#define CANSM_EXCLUSIVE_AREA_5   SCHM_EA_SUSPENDALLINTERRUPTS

#  define SchM_Enter_CanSM(ExclusiveArea) \
   SCHM_ENTER_EXCLUSIVE(ExclusiveArea)

#  define SchM_Exit_CanSM(ExclusiveArea) \
   SCHM_EXIT_EXCLUSIVE(ExclusiveArea)


#endif /* SCHM_CANSM_H */

